services:
    javer_influxdb.client.factory:
        class: Javer\InfluxDB\ODM\Client\ClientFactory

    javer_influxdb.odm.mapping.driver.attribute:
        class: Javer\InfluxDB\ODM\Mapping\Driver\AttributeDriver
        arguments:
            - '@javer_influxdb.odm.mapping.driver.attribute_reader'
            - ['%javer_influxdb.mapping_dir%']

    javer_influxdb.odm.mapping.driver.attribute_reader:
        class: Javer\InfluxDB\ODM\Mapping\Driver\AttributeReader

    javer_influxdb.repository.service_repository_factory:
        class: Javer\InfluxDB\Bundle\Repository\ServiceRepositoryFactory
        arguments:
            - !tagged_locator 'influxdb.repository_service'

    javer_influxdb.odm.measurement_manager:
        class: Javer\InfluxDB\ODM\MeasurementManager
        arguments:
            - '@javer_influxdb.odm.mapping.driver.attribute'
            - '@javer_influxdb.client.factory'
            - '@javer_influxdb.repository.service_repository_factory'
            - '%javer_influxdb.url%'
            - '%javer_influxdb.precision%'
            - '@?javer_influxdb.logger.influxdb'

    Javer\InfluxDB\ODM\Client\ClientFactoryInterface:
        alias: javer_influxdb.client.factory

    Javer\InfluxDB\ODM\Repository\RepositoryFactoryInterface:
        alias: javer_influxdb.repository.service_repository_factory

    Javer\InfluxDB\ODM\MeasurementManager:
        alias: javer_influxdb.odm.measurement_manager
