language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.4
    - php: 7.4
      env: DEPENDENCIES="symfony/config:^4.4 symfony/dependency-injection:^4.4 symfony/http-foundation:^4.4 symfony/http-kernel:^4.4 symfony/yaml:^4.4"
    - php: 7.4
      env: STABILITY="dev"

  allow_failures:
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpcs
